[package]
name = "nv-flip-sys"
version = "0.1.1"
authors = ["the gfx-rs developers"]
edition.workspace = true
rust-version.workspace = true
description = "FFI bindings to Nvidia Labs's ꟻLIP image comparison and error visualization library"
readme = "../README.md"
repository.workspace = true
license = "(MIT OR Apache-2.0 OR Zlib) AND BSD-3-Clause"
keywords = ["flip", "image-comparison", "nvidia", "ffi", "perceptual"]
categories = ["external-ffi-bindings", "graphics"]
links = "nv-flip"
include = [
    "src/",
    "extern/cpp/common/pooling.h",
    "extern/cpp/common/mapMagma.h",
    "extern/cpp/common/sharedflip.h",
    "extern/cpp/common/stb_image.h",
    "extern/cpp/common/stb_image_write.h",
    "extern/cpp/common/tinyexr.h",
    "extern/cpp/CPP/color.h",
    "extern/cpp/CPP/image.h",
    "extern/cpp/CPP/tensor.h",
    "build.rs"
]

[dependencies]

[dev-dependencies]
nv-flip = { path = "../nv-flip" }
image = { version = "0.25", default-features = false, features = ["png"]}
float_eq = "1"

[build-dependencies]
cc = "1"
