[package]
name = "nv-flip"
version = "0.1.2"
edition.workspace = true
rust-version.workspace = true
description = "High-Level bindings to Nvidia Labs's ꟻLIP image comparison and error visualization library"
readme = "../README.md"
repository.workspace = true
license = "MIT OR Apache-2.0 OR Zlib"
keywords = ["flip", "image-comparison", "nvidia", "error-visualization", "perceptual"]
categories = ["graphics", "multimedia::images", "visualization"]

[dependencies]
nv-flip-sys = { version = "0.1.0", path = "../nv-flip-sys" }

[dev-dependencies]
image = { version = "0.25", default-features = false, features = ["png"]}
float_eq = "1"
