name: CI

on:
  push:
  pull_request:

env:
  RUSTDOCFLAGS: -Dwarnings
  CI_RUST_VERSION: "1.84.0"

jobs:
  check-msrv:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows
          - name: Windows x86_64
            os: windows-2025

          # MacOS
          - name: MacOS x86_64
            os: macos-15

          # Linux
          - name: Linux x86_64
            os: ubuntu-24.04

    name: MSRV ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: install rust
        shell: bash
        run: |
          set -e

          rustup toolchain install ${{ env.CI_RUST_VERSION }} --no-self-update --profile=minimal --component clippy,rustfmt
          rustup override set ${{ env.CI_RUST_VERSION }}
          cargo -V

      - name: caching
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}

      - name: fmt
        shell: bash
        run: cargo fmt --check

      - name: clippy
        shell: bash
        run: cargo clippy -- -D warnings

      - name: test
        shell: bash
        run: cargo test

      - name: doc
        shell: bash
        run: cargo doc
